channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.8.8
  - pandas
  - numpy
  - numba
  - pymzml
  - pip:
    - lxml # for mzml parsing in pymzml
    - xmltodict
    - requests
    - requests_cache
    - tqdm
    - pyteomics
